### ISSUE TITLE
rild crash

### ISSUE THREAD

**Issue by GuaiYiHu** [tiger-cave/device_xiaomi_aries#2]
08-19 03:07:54.699  3737  3742 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3742 (rild)
08-19 03:07:54.701   326   326 I DEBUG   : property debug.db.uid not set; NOT waiting for gdb.
08-19 03:07:54.701   326   326 I DEBUG   : HINT: adb shell setprop debug.db.uid 100000
08-19 03:07:54.701   326   326 I DEBUG   : HINT: adb forward tcp:5039 tcp:5039
08-19 03:07:54.708   326   326 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-19 03:07:54.708   326   326 F DEBUG   : LineageOS Version: '13.0-20170818-UNOFFICIAL-aries'
08-19 03:07:54.708   326   326 F DEBUG   : Build fingerprint: 'Xiaomi/aries/aries:6.0.1/MMB29M/userdebug/release-keys'
08-19 03:07:54.708   326   326 F DEBUG   : Revision: '0'
08-19 03:07:54.708   326   326 F DEBUG   : ABI: 'arm'
08-19 03:07:54.708   326   326 F DEBUG   : pid: 1785, tid: 1799, name: rild  >>> /system/bin/rild <<<
08-19 03:07:54.708   326   326 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
08-19 03:07:54.709  1395  1859 W NativeCrashListener: Couldn't find ProcessRecord for pid 1785
08-19 03:07:54.716   326   326 F DEBUG   :     r0 b7b6f2d0  r1 00000000  r2 00000000  r3 00000002
08-19 03:07:54.716   326   326 F DEBUG   :     r4 00000000  r5 00000000  r6 b60c2528  r7 b60c2540
08-19 03:07:54.716   326   326 F DEBUG   :     r8 b664b004  r9 00000000  sl 00000000  fp b6e9b864
08-19 03:07:54.717   326   326 F DEBUG   :     ip b6deb5d8  sp b60c24d8  lr b6dbc2ed  pc b668eed6  cpsr 400f0030
08-19 03:07:54.726   326   326 F DEBUG   : 
08-19 03:07:54.726   326   326 F DEBUG   : backtrace:
08-19 03:07:54.726   326   326 F DEBUG   :     #00 pc 00000ed6  /system/lib/libqcci_legacy.so (qmi_client_init+25)
08-19 03:07:54.727   326   326 F DEBUG   :     #01 pc 00000e0d  /system/lib/libqminvapi.so (qmi_nv_read_mac_imp+168)
08-19 03:07:54.727   326   326 F DEBUG   :     #02 pc 00000e91  /system/lib/libqminvapi.so (qmi_nv_read_serial_number+8)
08-19 03:07:54.727   326   326 F DEBUG   :     #03 pc 001912cb  /system/lib/libril-qc-qmi-1.so (qcril_qmi_nas_dms_request_nv_data+86)
08-19 03:07:54.727   326   326 F DEBUG   :     #04 pc 00109925  /system/lib/libril-qc-qmi-1.so (qcril_qmi_nas_init+332)
08-19 03:07:54.727   326   326 F DEBUG   :     #05 pc 000fde43  /system/lib/libril-qc-qmi-1.so
08-19 03:07:54.727   326   326 F DEBUG   :     #06 pc 000fac39  /system/lib/libril-qc-qmi-1.so (qcril_qmi_client_init+1808)
08-19 03:07:54.727   326   326 F DEBUG   :     #07 pc 0006368b  /system/lib/libril-qc-qmi-1.so
08-19 03:07:54.727   326   326 F DEBUG   :     #08 pc 000632e7  /system/lib/libril-qc-qmi-1.so
08-19 03:07:54.727   326   326 F DEBUG   :     #09 pc 00055dd1  /system/lib/libril-qc-qmi-1.so (qcril_timed_callback_dispatch+36)
08-19 03:07:54.727   326   326 F DEBUG   :     #10 pc 00003f8d  /system/lib/libril.so
08-19 03:07:54.727   326   326 F DEBUG   :     #11 pc 00009139  /system/lib/libril.so (_Z14ril_event_loopv+496)
08-19 03:07:54.727   326   326 F DEBUG   :     #12 pc 00004eaf  /system/lib/libril.so
08-19 03:07:54.727   326   326 F DEBUG   :     #13 pc 00041ca7  /system/lib/libc.so (_ZL15__pthread_startPv+30)
08-19 03:07:54.727   326   326 F DEBUG   :     #14 pc 00018fbb  /system/lib/libc.so (__start_thread+6)

**Comment by javichampi** [comment]
Is ril bug solved finally??

**Comment by GuaiYiHu** [comment]
yup

**Comment by javichampi** [comment]
Oh great!! Which is the commit??? Congrats!!

P.D.: Sorry, I've found the commit right now in your proprietary vendor repository.
