### ISSUE TITLE
HWcomposer crashed on oreo

### ISSUE THREAD

**Issue by GuaiYiHu** [tiger-cave/device_xiaomi_aries#5]
12-01 09:36:02.658   685   685 E qdoverlay: Failed to call ioctl MSMFB_OVERLAY_SET err=Operation not permitted
12-01 09:36:02.658   685   685 E qdoverlay: MdpCtrl failed to setOverlay, restoring last known good ov info
12-01 09:36:02.658   685   685 E qdoverlay: == Bad OVInfo is:  mdp_overlay z=0 fg=0 alpha=255 mask=-1 flags=0x20000 id=-1
12-01 09:36:02.658   685   685 E qdoverlay: src msmfb_img w=736 h=1280 format=13 MDP_Y_CBCR_H1V2
12-01 09:36:02.658   685   685 E qdoverlay: src_rect mdp_rect x=0 y=0 w=720 h=1280
12-01 09:36:02.658   685   685 E qdoverlay: dst_rect mdp_rect x=0 y=0 w=720 h=1280
12-01 09:36:02.658   685   685 E qdoverlay: == Last good known OVInfo is:  mdp_overlay z=0 fg=0 alpha=0 mask=0 flags=0x0 id=-1
12-01 09:36:02.658   685   685 E qdoverlay: src msmfb_img w=0 h=0 format=0 MDP_RGB_565
12-01 09:36:02.658   685   685 E qdoverlay: src_rect mdp_rect x=0 y=0 w=0 h=0
12-01 09:36:02.658   685   685 E qdoverlay: dst_rect mdp_rect x=0 y=0 w=0 h=0
12-01 09:36:02.658   685   685 E qdoverlay: MdpCtrl Lkgo ov has id -1, will not restore
12-01 09:36:02.658   685   685 E qdoverlay: Ctrl commit failed set overlay
12-01 09:36:02.658   685   685 E qdhwcomposer: configure: configMdp failed for dpy 0
12-01 09:36:02.660   685   685 E qdhwcomposer: hwc_sync: ioctl MSMFB_BUFFER_SYNC failed, err=Operation not permitted
12-01 09:36:02.660   685   685 E qdhwcomposer: hwc_sync: acq_fen_fd_cnt=1 flags=0 fd=13 dpy=0 numHwLayers=4
12-01 09:36:02.660   685   685 E qdoverlay: Failed to call ioctl MSMFB_DISPLAY_COMMIT err=Operation not permitted
12-01 09:36:02.660   685   685 E qdoverlay: displayCommit: commit failed
12-01 09:36:02.660   685   685 E qdhwcomposer: hwc_set_primary: display commit fail for 0 dpy!
12-01 09:36:02.6

**Comment by gabrielgagz** [comment]
Sorry to bother you, but how did you fix this? I have a similar device with exactly the same problem....
I just upstreamed the video kernel drivers for msm and nothing....

**Comment by GuaiYiHu** [comment]
Fixed...

**Comment by dkati** [comment]
@GuaiYiHu do u remember what the fix was ?

**Comment by NotNoelChannel** [comment]
i need the fix too, can someone give me the commit?
